ecourses/courses/urls.py
from django.contrib import admin
from django.urls import path,include
from django.http import HttpResponse
from courses.views import home,coursePage,CreateForm,checkout,verifyPayment
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
# def home(request):
#     return HttpResponse("Home page")
app_name="courses"
urlpatterns = [
    
    path('',home,name='home'),
    path('signup/',CreateForm.as_view(),name='signup'),
    path('course/<str:slug>',coursePage,name='coursePage'),
    path('check-out/<str:slug>',checkout,name='check-out'),
    path('login/',auth_views.LoginView.as_view(template_name='courses/login.html'),name='user_login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('verify_payment',verifyPayment,name='verify_payment'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecourses/ecourses/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("courses.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecourses/courses/models/course.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Course(models.Model):
    name=models.CharField(max_length=50,null=False)
    slug=models.CharField(max_length=50,null=False,unique=True)
    discription =models.CharField(max_length=2000,null=True)
    price=models.IntegerField(null=False)
    discount=models.IntegerField(null=False,default=0)
    active=models.BooleanField(default=False)
    thumbnail=models.ImageField(upload_to="files/thumbnail")
    date=models.DateTimeField(auto_now_add=True)
    resource=models.FileField(upload_to='files/resource')
    length=models.IntegerField(null=False)
    def __str__(self) -> str:
        return self.name
    
class CourseProperty(models.Model):
    discription=models.CharField(max_length=100,null=False)
    course=models.ForeignKey(Course,null=False,on_delete=models.CASCADE)
    
    class Meta():
        abstract=True
    
    
class Tag(CourseProperty):
    pass
    
class Prerequisite(CourseProperty):
    pass
    
class Learning(CourseProperty):
    pass

class Customuser(AbstractUser):
    email=models.EmailField()


    def __str__(self):
       return self.username
   

ecourses/courses/models/payment.py
from django.db import models
from django.contrib.auth.models import User
from courses.models import Course,UserCourse
from django.conf import settings
from django.contrib.auth.models import User

class Payment(models.Model):
    order_id=models.CharField(max_length=50,null=False)
    payment_id=models.CharField(max_length=50)
    user_course=models.ForeignKey(UserCourse,null=True,blank=True,on_delete=models.CASCADE)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)
    status=models.BooleanField(default=False)

ecourses/courses/models/user_course.py
from django.db import models
from django.contrib.auth.models import User
from courses.models import Course
from django.conf import settings

class UserCourse(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,null=False,on_delete=models.CASCADE)
    course=models.ForeignKey(Course,null=False,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f'{self.user.username}-{self.course.name}'

ecourses/courses/models/video.py
from django.db import models
from courses.models import Course
class Vedio(models.Model):
    title=models.CharField(max_length=100,null=False)
    course=models.ForeignKey(Course,null=False,on_delete=models.CASCADE)
    serial_number=models.IntegerField(null=False)
    vidio_id=models.CharField(max_length=100,null=False) 
    is_preview=models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return self.title
    

ecourses/courses/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from courses.models import Customuser

class Form(UserCreationForm):
    class Meta:
        model = Customuser
        fields = ['username', 'email', 'password1', 'password2']

ecourses/courses/views/checkout.py
from django.shortcuts import render, get_object_or_404, redirect
from courses.models import Course,Payment,UserCourse
from django.conf import settings
from django.http import HttpResponse
from django.urls import reverse
from ecourses.settings import KEY_ID, KEY_SECRET
from time import time
import razorpay
from django.views.decorators.csrf import csrf_exempt

client = razorpay.Client(auth=(KEY_ID, KEY_SECRET))

def checkout(request, slug):
    course = Course.objects.get(slug=slug)
    user = None
    payment=None
    if not request.user.is_authenticated:
        return redirect(reverse('courses:user_login'))
    user = request.user

    action = request.GET.get('action')
    order = None
    error=None
    if action == 'create_payment':
        try:
            user_course=UserCourse.objects.get(user=user,course=course)
            error="You are Already Enrolled in this Course"
        except:
            pass
        if error is None:
            amount = int((course.price - (course.price * course.discount * 0.01)) * 100)
            currency = "INR"
            notes = {
                "email": user.email,
                "name": f'{user.first_name} {user.last_name}'
            }
            receipt = f"ecourses-{int(time())}"
            order = client.order.create({
                'receipt': receipt,
                'notes': notes,
                'amount': amount,
                'currency': currency
            })
            payment=Payment()
            payment.user=user
            payment.order_id=order.get('id')
            # payment.user_course=
            payment.course=course
            payment.save()
    context = {
        "course": course,
        "order": order,
        "payment":payment,
        "error":error,
    }
    return render(request, 'courses/check-out.html', context=context)

@csrf_exempt
def verifyPayment(request):
    if request.method=="POST":
        data=request.POST
        print(data)
        context={}
        try:
            client.utility.verify_payment_signature(data)
            razorpay_order_id=data['razorpay_order_id']
            razorpay_payment_id=data['razorpay_payment_id']
            payment=Payment.objects.get(order_id=razorpay_order_id)
            payment.payment_id=razorpay_payment_id
            payment.status=True
            usercourse=UserCourse(user=payment.user,course=payment.course)
            usercourse.save()
            print("Usercourse",usercourse)
            payment.user_course=usercourse
            payment.save()
            return render(request,'courses/mycourses.html',context=context)
        except:
            return HttpResponse("Sorry, there was an error.")
    

ecourses/courses/views/courses.py
from django.shortcuts import render, get_object_or_404,redirect
from courses.models import Course, Vedio,UserCourse
from django.http import HttpResponse
from django.urls import reverse

def coursePage(request, slug):
    print(slug)
    print(request.user)
    course = Course.objects.get(slug=slug)
    serial_number = request.GET.get('lecture')
    vedios = course.vedio_set.all().order_by("serial_number")
    
    video = None
    if serial_number:
        video = get_object_or_404(Vedio, serial_number=serial_number, course=course)
    if video and not video.is_preview:
        if not request.user.is_authenticated:
            return redirect('courses:user_login')
        else:
            user = request.user
            try:
                user_course = UserCourse.objects.get(user=user, course=course)
            except:
                return redirect('courses:check-out', slug=course.slug)
    context = {
        "course": course,
        "vedio": video,
        "vedios": vedios,
    }
    return render(request, 'courses/course_page.html', context=context)

ecourses/courses/views/homepage.py
from django.shortcuts import render
# from django.http import HttpResponse
from courses.models import Course

def home(request):
    courses=Course.objects.all()
    print(courses)
    return render(request,'courses/home.html',{"courses":courses})
    


ecourses/courses/templates/courses/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load bootstrap3 %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'courses/css/m.css' %}">
    <script async src="https://ga.jspm.io/npm:es-module-shims@1.6.3/dist/es-module-shims.js" crossorigin="anonymous"></script>
    <script async src="https://ga.jspm.io/npm:es-module-shims@1.6.3/dist/es-module-shims.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script type="importmap">
        {
            "imports": {
                "three": "https://unpkg.com/three@0.154.0/build/three.module.js",
                "three/addons/": "https://unpkg.com/three@0.154.0/examples/jsm/"
            }
        }
    </script>
    <title>Stylish White Nav Bar</title>
    <style>
        /* Custom styles */
       

        .navbar-brand {
            
            font-size: 30px;
            font-weight: bold;
        }

        .navbar-nav .nav-link {
            
        }

        .navbar-nav .nav-link:hover {
            
        }

        /* Additional styles for the upper navbar */
        .upper-navbar {
            background-color: transparent;
            
            padding: 10px 0;
        }

        .upper-navbar a {
            
            margin-right: 20px;
            text-decoration: none;
        }

        .upper-navbar{
            font-size: 24px;
            font-weight: bold;
        }

        /* Add some styles to the container */
        #heee {
            padding: 20px;
            border-radius: 10px;
            background-color: #f8f9fa;
            margin-top: 20px;
            box-shadow: 0 0 10px lightpink;
            
        }
        
       
    </style>
</head>
<body class="loader">

    <nav class="navbar">
        <a class="navbar-brand" href="{% url 'courses:home' %}">Ecourses</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="upper-navbar">
            <div class="container" style="background-color: transparent;">
                <div class="row justify-content-end">
                    <div class="col-auto">
                        <a href="{% url 'courses:home' %}">Home</a>
                        {% if user.is_authenticated %}
                        <a href="/logout">Logout</a>
                        {% else %}
                        <a href="/signup">Signup</a>
                        <a href="/login"><i class="fas fa-user"></i></a>
                        {% endif%}
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <div class="container" id="heee">
        {% block content%}
        {% endblock %}
    </div>
</body>
<script src="{% static 'courses/js/basic.js' %}"></script>
</html>

ecourses/courses/templates/courses/check-out.html
{% extends 'courses/base.html' %}
{% load course_custom_tags %} 
{% load bootstrap3 %}
{% block title %}
CHECK-OUT
{% endblock %}
{% block content %}
<div class="container" id="heee">
    
    <br>
    <div class="row justify-content-center">
        <div class="col-md-5 mb-4">
            <div class="card"style="height:300px;width:250px">
                <img src="{{ course.thumbnail.url }}" class="card-img-top" alt="{{ item.name }}" style="max-width: 200px; height: 150px;">
                <div class="card-body">
                    <h5 class="card-title">{{ course.name }}</h5>
                    <p class="card-text m-0 p-0">
                        <p> Save {{ course.discount }}%</p>
                        <p class="price"><del>{{ course.price|rupee }}</del>
                            &nbsp;
                            <span> {% calculate_total_price course.price course.discount as value %}{{ value|rupee }}</span></p>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-5 mb-4">
            <div class="checkout-details ">
                <div class="card-body">
                    <h2 class="card-title">Checkout Summary</h2>
                    <p>Course: {{ course.name }}</p>
                    <p>Payable Amount: {{ value|rupee }}</p>
                    <a class="btn btn-light border" href="?action=create_payment">Continue to payment</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% if order is not None%}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_y90krNyeQPoxaY", // Enter the Key ID generated from the Dashboard
     // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    
    "name": "ecourses", //your business name
    "description": "Payment For{{course.name}}",
    "image": "https://lessonpros.com/wp-content/uploads/2017/11/ecourses-logo-1.png",
    "order_id": "{{order.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "http://127.0.0.1:8000/verify_payment",
    "prefill": { //We recommend using the prefill parameter to auto-fill customer's contact information especially their phone number
        "name": "{{request.user.username}}", //your customer's name
        "email": "{{request.user.email}}",
     //Provide the customer's phone number for better conversion rates 
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.open(); 
</script>
{% endif%}
{% if error is not None%}
<script>
    window.onload=()=>{
        alert('{{error}}')
    }
</script>
{% endif %}
{% endblock %}

ecourses/courses/templates/courses/course_page.html
{% extends 'courses/base.html' %}
{% load static %}
{% block content %}
<div class="containeri" id="heee">
    {% comment %} {{vedio.vidio_id}} {% endcomment %}
    <div class="row">
        <div class="col">
            <div class="iframe-container">
                <iframe src="https://www.youtube.com/embed/{{vedio.vidio_id}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>
        </div>
        
        <div class="col-3">
            <div class="video-list-container">
                <ul id='vedio_list' class="list-group">
                    {% for vedio in vedios %}
                    <li class="list-group-item {% if vedio.name|length > videoHeight %}scrollable{% endif %}">
                        <a class="vedio-name" href="?lecture={{ vedio.serial_number }}">{{vedio}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% comment %} Courses detail's {% endcomment %}
        <div class="mt-3">
            <!-- card_template.html -->

            <div class="card">
                <div class="card-header">
                    <h2>{{ course.name }}</h2>
                </div>
                <div class="card-body">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia molestiae nobis sed aliquid, dolorem at quas error culpa odit tempora mollitia, aliquam modi numquam, deleniti minus aperiam ullam neque sapiente.</p>
                    <p><strong>{{ course.discription }}</strong></p> 
                    {% comment %} <p><strong>Occupation:</strong> {{ person.occupation }}</p> {% endcomment %} 
                </div>
            </div>
        </div>
        <div class="mt-3">
            <!-- card_template.html -->

            <div class="card">
                <div class="card-header">
                    <h2>Prerequisite Required:</h2>
                </div>
                <div class="card-body">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia molestiae nobis sed aliquid, dolorem at quas error culpa odit tempora mollitia, aliquam modi numquam, deleniti minus aperiam ullam neque sapiente.</p>
                    <p class="card-text">
                        {% for pre in course.prerequisite_set.all%}
                        
                        <li><strong>{{pre.discription}}</strong></li>
                        
                        {% endfor %}
                    </p>
            </div>
        </div>
        <div class="mt-3">
            <!-- card_template.html -->

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Learning Material:</h5>
                    <p class="card-text">
                        {% for pre in course.learning_set.all%}
                        <ol>
                        <li>{{pre.discription}}</li>
                        </ol>
                        {% endfor %}
                    </p>
            </div>
        </div>

    </div>
</div>
<script src="{% static 'courses/js/basic.js' %}"></script>
{% endblock %}

ecourses/courses/templates/courses/home.html
{% extends 'courses/base.html' %}
{% load course_custom_tags %} 
{% load static %}
{% block content %}
    <div class="container mt-4" id="heee">
        <div class="row">
            {% for item in courses %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ item.thumbnail.url }}" class="card-img-top" alt="{{ item.name }}" style="max-width: 200px; height: 150px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.name }}</h5>
                        <p class="card-text m-0 p-0">
                            <p> Save {{ item.discount }}%</p>
                            <p class="price"><del>{{ item.price|rupee }}</del>
                                &nbsp;
                                <span> {% calculate_total_price item.price item.discount as value %}{{ value|rupee }}</span></p>
                        </p>
                    </div>
                    <div class="card-footer p-0">
                        {% is_enrolled request item  as enrolled %}

                        {% if enrolled %}
                        <div class="col border-right-1">
                            <a class="btn btn-light btn-block" href="/course/{{ item.slug }}">Start Course</a>
                        </div>
                        {% else %}
                        <div class="row">
                            <div class="col border-right-1">
                                <a class="btn btn-light btn-block" href="/check-out/{{item.slug}}">Enroll Now</a>
                            </div>
                            <div class="col border-left-1">
                                <a class="btn btn-light btn-block" href="/course/{{ item.slug }}">Show More</a>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

ecourses/courses/templates/courses/login.html
{% extends 'courses/base.html' %}
{% load bootstrap3 %} <!-- Load the Bootstrap3 library -->
{% block content %}
<div class='container' id="heee">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="login" class="btn btn-primary">
    </form>
</div>
{% endblock %}

ecourses/courses/templates/courses/mycourses.html
{% extends 'courses/base.html' %}
{% load course_custom_tags %} 
{% load bootstrap3 %}
{% block title %}
CHECK-OUT
{% endblock %}
{% block content %}
<h1>My courses</h1>
{% endblock%}

ecourses/courses/templates/courses/signup.html
{% extends 'courses/base.html' %}
{% load course_custom_tags %} 
{% load bootstrap3 %}
{% block title %}
Signup
{% endblock %}
{% block content %}
<div class='container' id="heee">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="SignUp" class="btn btn-primary">
    </form>
</div>

{% endblock%}